### ISSUE TITLE
fuse_session_new() fails if fuse_args is empty (argc == 0)

### ISSUE THREAD

**Issue by heroin-moose** [libfuse/libfuse#100]
I use lowlevel API to create a filesystem and I (for now) do not pass any options to it. Seems like fuse_session_new() does not like it, because it prints an error message

`fuse: unknown option(s):`'`

and returns me NULL. The issue is argc verification code that checks for argc not being equal to zero instead of checking that argc is greater than zero.

**Comment by heroin-moose** [comment]
Patch: https://gist.github.com/heroin-moose/521fdf1b360854d773ca58cff4335c57

**Comment by Nikratio** [comment]
This is a sort-of feature. If you start with an empty argument vector, chances are that when you add an argument in the future you will put it into argv[0] - and then it will be ignored, because argv[0] is assumed to be the program name that should *always* be present.

But this should be better documented. I may also add a check to print a warning if the program name happens to start with a dash...

**Comment by heroin-moose** [comment]
Hmm... So I should fill in argv[0] and all should be fine? Okay, seems reasonable. The thing is -- I'm writing a multi-threaded daemon that is able to create/delete filesystems on-demand, so there is no argv passed by user (only options passed by mount.<fs>). Is this approach is okay with libfuse? E.g. I see that it logs to stderr so I have to patch it a little in order to add ability to pass my own logger function.

**Comment by Nikratio** [comment]
Yes, that's ok. You can even pass NULL as argv[0].
