### ISSUE TITLE
Incorrect errno after calling readdir

### ISSUE THREAD

**Issue by martijnotto** [libfuse/libfuse#141]
If I call fuse_reply_err(req, EIO) from a readdir call, this shows up as EACCES to the user. Why is the error code changed?

**Comment by Nikratio** [comment]
Most likely because there is no direct correspondence between the readdir() call from userspace and your readdir() handler. Multiple userspace readdir() calls can be handled by a single FUSE readdir(), and vice versa. Thus is wouldn't be clear which error to return.

Note that this happens in the kernel, libfuse is not doing anything special (and thus can't affect the behavior either).

**Comment by martijnotto** [comment]
So basically what you are saying is that the kernel takes the readdir request, turns it into multiple requests and then sends it to FUSE? Wouldn't it be sensible to simply return the first error that was encountered? It seems rather unlikely that those multiple calls somehow return different error numbers and in any case, it would be better than the current situation (returning an error that never occured).

**Comment by Nikratio** [comment]
I'm not taking a stance on this. It's a linux kernel thing :-).
