### ISSUE TITLE
Specify *process* uid+gid or user+group to mount.fuse

### ISSUE THREAD

**Issue by tfiskgul** [libfuse/libfuse#144]
Hello,

First off, thanks for a great project! Extending the Unix philosophy of "everything-is-a-file" is a powerful tool =)

I would like to mount a FUSE file-system via /etc/fstab, but I don't want the resulting user space process running as root. I don't want the uid / gid mount flags to override the uid or gid on the mounted file-system, but rather keep experimental file-systems running as non-root.

Is it possible to introduce some parameter like run-uid and run-gid? So that when the mount command from fstab runs as root, passes -o run-uid <id> to mount.fuse, which then does a setuid() syscall before invoking the FS and mounting.

The reasoning is:
* I want to auto mount the FS via /etc/fstab, and use the convenience there-in, not having to mount the FS in a shell script handled on the side.
* I want the FUSE FS process to run as non-root, to reduce attack surface, in case of bugs.

Is this feasible to do, or is the concept flawed?

**Comment by trapexit** [comment]
What filesystem is this? Be sure that it works as non-root in the way you
would want first. Secondly I'd suggest requesting the author of the
filesystem to implement that. There is already (at least in pre v3.0
libfuse) a lot of functional bleedthrough which can screw up a filesystem
if it's not managed handled explicitly by the author.

There are other ways to start services which could work as well and would
be technically more appropriate but may depend on the OS.

**Comment by tfiskgul** [comment]
The filesystem would primarily  be one that I'm developing at the moment, and  [rar2fs](https://github.com/hasse69/rar2fs).

Both have been tested and work as non-root. Yes, the setuid() could be implemented in both, but I think other FUSE implementations could benefit from this functionality as well.

The beauty and philosophy of FUSE to implement filesystems in user space instead of kernel space provides advantages such as more isolation and reduced attack surface. The same reasoning and arguments could be applied to the functionality of dropping from root to a normal user before mount.

**Comment by trapexit** [comment]
Kernel vs userspace is different from root vs not. Besides it's better that
the library do as little as possible in general and especially from the
user perspective. There are command line arguments which break filesystems
because the authors don't intend them to be used and there isn't a built in
way to manage it. The library should manage only that which is must and
those things configurable should be controlled by the filesystem. Not the
user. And to that end libfuse 3 has moved to removing arguments that should
be controlled by the filesystem rather than user and setuid/setgid is not a
concern to FUSE itself and could be problematic to give users arbitrary
control over.

fstab is a root controlled file. System services are also multi user and
therefore generally run as root or need to be started as root. Individual
users have their own ways to run software on login. It is best handled by
the filesystem and quite trivial to implement.

FUSE filesystems which must run as a specific user or are narrowly scoped
like rar2fs should be run by the user anyway. They aren't system level
services.

**Comment by tfiskgul** [comment]
Thanks for the quick and well formulated feedback, I understand your standpoint and concerns regarding breaking existing filesystems. I will find another way to mount the filesystems using a non-root user.

**Comment by tfiskgul** [comment]
In case you're interested, I concocted this travesty of a shell script hack as a workaround:

This file is placed as /sbin/mount.ufuse, and filters the two options "run-uid" and "run-gid" to pass them to sudo and delegate on to the real mount.fuse binary.

[/sbin/mount.ufuse] (https://gist.github.com/tfiskgul/736685815c84ab7439ce08ca15b3b258)


It works from /etc/fstab as intended;
```
source	target	ufuse.rar2fs	run-uid=1000,run-gid=1000,nofail,ro,nosuid,nodev,default_permissions,allow_other
```

The resulting rar2fs is no longer run as root, instead running as uid 1000 and gid 1000:
```
$ ps aux -H | grep rar2fs
user     6809  0.0  0.0 101888   852 ?        Ssl  19:58   0:00   rar2fs source target -o ro,nosuid,nodev,default_permissions,allow_other
```

The old fuse.rar2fs mount procedure is untouched, and still works for FS:s that I want to run as root.

I know this is terrible and ugly, and probably insecure, but it works for now =)
