### ISSUE TITLE
FUSE could avoid some calls to userspace for extended attribute operations

### ISSUE THREAD

**Issue by jjobi** [libfuse/libfuse#150]
If there is a way to tell the FUSE kernel module that some inodes don't have xattrs, so that any xattr requests for these inodes can be handled in-kernel without being send to the userspace
process.

Currently, it looks like there are too many getxattr/listxattr/removexattr
calls being made on files which does not have any extended attributes,
those are coming from many unix commands like ls etc..  I am wondering
if we could add a new field to struct fuse_entry_param or something
equivalent to denote the file does not have any extended attributes and
 such information can be cached by the kernel along with rest of the file
attributes.  So after normal getattr()/lookup() call, the kernel can avoid
subsequent calls to getxattr()/removexattr() if the file does not have any
extended attributes.

When I run "ls -l" in a directory with 10000 files in it, fuse library is
getting 10000 lookup calls and 20000 getxattr calls.
As these files don't have any extended attributes, getxattr calls are
returning immediately, but only after looking up the corresponding inode
and taking a shared lock on it.
For the time being, I can avoid looking up the inode if a file system does
not have any extended attributes, but that optimization does not work if
some files have extended attributes.
Also the cost of roundtrip getxattr call from kernel to fuse library cannot
be avoided that way.  Here are the count of various fuse library calls made
when "ls -l" is invoked on a directory with 10000 files in it.
Overall, I would say the performance gain would be 10-20% if these
unnecessary getxattr calls are skipped.

                 LOOKUP:      10000
                GETATTR:          2
                OPENDIR:          1
                READDIR:         80
             RELEASEDIR:          1
               GETXATTR:      20000

I just wrote a small program to create a directory and invoke removexattr
on it and I can see removexattr is sent to userspace.  There are many unix commands which does removexattr calls on files which do not have any extended attributes.

Here are the fuse logs.

unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 116314
   unique: 2, success, outsize: 120
unique: 3, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 116314
   unique: 3, error: -38 (Function not implemented), outsize: 16
unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 42, pid: 116314
   unique: 4, success, outsize: 144
unique: 5, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 67887
   unique: 5, success, outsize: 144
unique: 6, opcode: MKDIR (9), nodeid: 1, insize: 52, pid: 67887
   unique: 6, success, outsize: 144
unique: 7, opcode: REMOVEXATTR (24), nodeid: 3, insize: 45, pid: 67887
   unique: 7, error: -61 (No data available), outsize: 16

**Comment by Nikratio** [comment]
Thanks for the suggestion! Having this implemented in would indeed be nice. Please note that this feature (just like the one from issue #151) has been discussed on the fuse mailing list a little while ago. I'd suggest to read-up on the discussion if you haven't done so already.

That said, please note that libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Feature requests are therefore in general unlikely to actually result in the feature being implemented.

Would you be interested in working on this? If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).
