### ISSUE TITLE
Requesting an option to invalidate kernel page cache when a file is closed

### ISSUE THREAD

**Issue by jjobi** [libfuse/libfuse#151]
Currently, fuse has an option to invalidate pages of a file in kernel
page cache as part of open(2) - by not setting keep_cache.  I am wondering if another
option can be provided to do the same (invalidate pages in page cache) as
part of last close(2) on the file.  Then we can avoid an explicit
notify_inval calls from release callback, in situations where pages in
kernel page cache are not desired when file is no longer open.

Currently, FUSE invalidates pages on open, not on close.  So if a file is
not opened anymore, its pages may remain cached in kernel page cache for longer
periods.

I noticed this while implementing a snapshot/overlay file system in which data is shared between
files in the snapshots.
The files in snapshots would have different file handles (snapshot number +
inode number) and kernel cannot detect duplicate data and all those will
flood up the page cache.
So it needed to keep the impact on the kernel page cache to the very minimum
by invalidating the kernel page cache as quickly as possible.
Otherwise, there will be too much pressure on the kernel page cache and
system memory, and useful data from the page cache may be thrown out and
swapping may kick in.

It may be ok for the kernel to cache pages while the file is open, but should
be invalidated at the time of close since you never know whether there will
be another open on the same file again soon.
So if the file is not opened again, the pages may hang around in the page
cache longer than desired.
So rather than waiting for the next open to invalidate the pages, it would be good to
 have the pages invalidated in kernel page cache at the time of
close.
Also fuse file systems may have its own page cache maintained and don't
want pages to be cached in two places for longer periods.

**Comment by Nikratio** [comment]
Thanks for the suggestion! Having this implemented in would indeed be nice. Please note that this feature has been discussed on the fuse mailing list a little while ago. I'd suggest to read-up on the discussion if you haven't done so already.

That said, please note that libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Feature requests are therefore in general unlikely to actually result in the feature being implemented.

Would you be interested in working on this? If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).
