### ISSUE TITLE
Requesting an option to bypass kernel page cache when a file is not mmapped

### ISSUE THREAD

**Issue by jjobi** [libfuse/libfuse#152]
Fuse options for direct I/O (using direct_io mount option or setting that in file handle) for bypassing kernel page cache will break mmap(2).  As a fuse file system does not know whether a file is mmapped or not, it has no means to effectively use direct I/O bypassing kernel page cache.  It would be good to have new option which will do direct I/O on files, without breaking mmap(2) support - meaning direct I/O will be used on files which are not memory mapped and regular I/O on files which memory mapped files.  This would be useful for file systems which don't want their data cached in kernel page cache unless when needed for mmap(2) (for reasons like they may have their own page cache and things of that sort).

**Comment by Nikratio** [comment]
Thanks for the suggestion! Having this implemented would indeed be nice.

That said, please note that libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Feature requests are therefore in general unlikely to actually result in the feature being implemented.

Would you be interested in working on this? If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).
