### ISSUE TITLE
Fuse force off_t to 64bit, and what happened with size_t?

### ISSUE THREAD

**Issue by rmbeer** [libfuse/libfuse#171]
Well, any forget about of size_t. Where fuse force change the off_t from 32bit to 64bit, the size_t still is 32bit. Not have sense a offset very big in the little size...
Fuse must also force the size_t to 64bit or use all default from the system?
For 64bit also can adapt the fuse to stat64 and other options for 64bits. The force of off_t to 64 is a very bad idea...

**Comment by trapexit** [comment]
Why is it bad? It's the standard way to deal with large files. And what instances of size_t? There is no reason they need to be the same size unless conversion between the two expect them to be the same size.

**Comment by rmbeer** [comment]
Why the size_t only take to 4GB and not more. Is about of size of the file, or always use off_t for the size and offset of the file?

**Comment by trapexit** [comment]
What are you referring to? The APIs for FUSE should and generally do mimic and match that of the standard API calls in their normal usage.

**Comment by Rondom** [comment]
`size_t` is not "about the size of a file", but about the size of an object in memory. `off_t`refers to the size of a file. FUSE follows established standards and practice here.

**Comment by Nikratio** [comment]
@rmbeer , I am not sure what you are trying to say. Are you trying to compile libfuse on a system where `off_t` is not 64 bits? What kind of system is that?

I'm closing this issue for now, since even if there was a good reason, there would be no way to make libfuse3 support a 32 bit off_t without breaking backwards compatibility (since existing fuse filesystems may already depend on off_t being 64 bit). And the barrier for a libfuse4 is *very* high.

I'd suggest to continue this discussion the fuse mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel).
