### ISSUE TITLE
Can't hardlink unix domain sockets 

### ISSUE THREAD

**Issue by sloonz** [libfuse/libfuse#199]
On other filesystems, if `a` is a UNIX socket, then after `link("a","b")` `a` and `b` refers to the same socket. It looks like FUSE can't properly handle this. Using `passthrough_fh` : 

```
$ mkdir /tmp/testfs
$ ./passthrough_fh /tmp/testfs
$ cd /tmp/testfs/tmp
$ socat UNIX-LISTEN:testsocket.a STDIO &
$ ln testsocket.a testsocket.b
$ socat UNIX:testsocket.b STDIO
2017/08/14 14:05:26 socat[19268] E connect(5, AF=1 "testsocket.b", 12): Connection refused
```

**Comment by Nikratio** [comment]
That's most likely not a limitation of libfuse, but of the high-level API. I'd tell you to test with the passthrough_ll instead, but IIRC that doesn't support sockets...

**Comment by Nikratio** [comment]
To be more precise, I suspect this isn't working because the high-level API copes badly with hardlinks. And if the kernel doesn't know that the two sockets are hardlinks of each other, it won't connect them.

What's your actual use-case? I suppose it's not running the example filesystems, so testing this on the filesystem you actually want to use may just work.

**Comment by sloonz** [comment]
I discovered the bug by using [rewritefs](https://github.com/sloonz/rewritefs) on my home directory. Ansible, trying to use ssh multiplexed connection, fails, because SSH does this to setup the control socket : 

```
$ strace -e file ssh -M -o ControlPath=/tmp/sshcp.sock root@backupsrv exit
bind(5, {sa_family=AF_UNIX, sun_path="/tmp/sshcp.sock.FzWcKyxzNrK9jPlT"}, 110) = 0
link("/tmp/sshcp.sock.FzWcKyxzNrK9jPlT", "/tmp/sshcp.sock") = 0
unlink("/tmp/sshcp.sock.FzWcKyxzNrK9jPlT") = 0
```

It then tries to connect to the control socket on `/tmp/sshcp.sock`, which fails.

There’s an obvious solution to this particular issue, which is changing the control socket path to somewhere in /tmp, but I’m wondering if a cleaner fix is possible.

**Comment by Nikratio** [comment]
I just tried this again using the low-level API by executing the mknod and link on the underlying filesystem, and it still does not work:

```
$ ./passthrough_ll ~/tmp/mnt
$ (cd /tmp; socat UNIX-LISTEN:testsocket.a STDIO) &
$ (cd /tmp; ln testsocket.a testsocket.b)
$ (cd ~/tmp/mnt/tmp; socat UNIX:testsocket.b STDIO
2017/08/17 10:17:46 socat[9664] E connect(5, AF=1 "testsocket.b", 14): Connection refused
```

...so probably using the low-level API isn't enough either. The issue is most likely in the kernel then, which I'm not really familiar with. If you want to get this addressed, I'd suggest to write to the linux-fsdevel mailing list.

**Comment by szmi** [comment]
In the above example you are opening testsocket.a on /tmp and testsocket.b on ~/tmp/mnt/tmp.  Is this intentional?  Because that will NOT work, the two files have nothing to do with each other.

Using ~/tmp/mnt/tmp/testsocket.a and ~/tmp/mnt/tmp/testsocket.b *should* work.

**Comment by Nikratio** [comment]
I don't follow. passthrough_ll mirrors / into ~/tmp/mnt, so /tmp/ and ~/tmp/mnt/tmp are the same directory.

Running both socat instances in the FUSE mountpoint doesn't work, probably because the passthrough_ll example is missing some handlers:

```
$ ./passthrough_ll ~/tmp/mnt
$ cd /tmp/mnt/tmp
$ socat UNIX-LISTEN:testsocket.a STDIO 
2018/07/27 08:46:38 socat[32700] E bind(5, {AF=1 "testsocket.a"}, 14): Function not implemented
```

**Comment by szmi** [comment]
A filesystem object uniquely identified by {st_dev, st_ino} pair within an operating system instance.  Look at the socket on /tmp and the *mirror* of it, which is in the fuse mount:

$ stat -c "{%d,%i}" /tmp/testsocket.a 
{43,2151085}
$ stat -c "{%d,%i}" ~/mnt/fuse/tmp/testsocket.a 
{45,2151085}

So they are not the same object, and hence the OP is stating the expected and correct behavior.

The failure on passthrough_ll is because of missing ->mknod() op.  We have a patch to fix that, will post a series for passthrough_ll improvements later.

**Comment by Nikratio** [comment]
Ah, that makes sense. It didn't occur to me that st_dev is relevant here as well. Thanks!
