### ISSUE TITLE
old style mounting not supported

### ISSUE THREAD

**Issue by chrisophia** [libfuse/libfuse#220]
when i used the command 'fusermount', it printf "old style mounting supported", how to fix it? thank you.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

(It would probably be a good idea to also mention what you expect fusermount to do)
