### ISSUE TITLE
FUSE_READDIR_PLUS, where is the performance benefit ?

### ISSUE THREAD

**Issue by benrubson** [libfuse/libfuse#239]
Hi,

When using `FUSE_READDIR_PLUS`, we can pass the `FUSE_FILL_DIR_PLUS` to the `filler()` function so that Fuse will not stat the entry. It will then take the info from the stat structure given to `filler()`. 
Perfect.

However, to fill the stat structure, we first then have to stat the file.
So finally we stat directly in the `readdir()` loop, instead of Fuse itself after `filler()` has been called.
A nice example in the `FUSE_READDIR_PLUS` commit : https://github.com/libfuse/libfuse/commit/6bf2e6f07c133f7b145a4726c5d962f14c650ca7#diff-3dfe31723d6e7e29f3239b815df0855eR156

What are the benefits then in terms of performance, if file needs to be stated ?

Thank you very much 👍 

Ben

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.
