### ISSUE TITLE
Fuse release is it sync or async?

### ISSUE THREAD

**Issue by sudeep9** [libfuse/libfuse#243]
I was reading the [link about release](https://lwn.net/Articles/613186/). It says that release is async operation. Since it is a old article, is this still the case?

**Context:** I want to expose Fuse FS via NFS. Since NFS v3 does not have open/close RPCs, my fuse FS gets multiple open/close. I want to detect last release by maintaining ref-count per ino. If it reaches == 1 then I will do something special in close(). However, it can fail as well. I need release() to be synchronous for my FS. 

Now I am aware that fuse does not check return value of release() but I have a work-around for that.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

**Comment by sudeep9** [comment]
Noted. I have sent it to the mailing list.
