### ISSUE TITLE
Unecessary chdir() in fuse_daemonize?

### ISSUE THREAD

**Issue by emsaks** [libfuse/libfuse#257]
The code in `helper.c` for `fuse_daemonize` calls `chdir()` to set the working directory to root "\\". Is this necessary, and can the filesystem safely change the working directory after returning from `fuse_daemonize`?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

In short, this is good practice for daemons, but you can change it afterwards.
