### ISSUE TITLE
Is FUSE as whole thread safe? (Is it singleton)

### ISSUE THREAD

**Issue by lapsio** [libfuse/libfuse#258]
Is FUSE as whole filesystem singleton in realms of single process? What i mean is - is it possible (safe) to call `fuse_main()` twice in single process in two (or more) threads, creating multiple mountpoints in single process?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

In short: no, calling fuse_main() simultaneously is not supported. You can use the lower level functions though.
