### ISSUE TITLE
The thread calls fuse_main, how to exit the blocked fuse_main？

### ISSUE THREAD

**Issue by linyuan870** [libfuse/libfuse#262]
A main thread newly opened a thread called fuse_main mount, I want to be able to control the thread call fuse_main exit（After the thread calls fuse_main, fuse_main blocks until there is a method to make it exit this blocking）; how to do it? For example, the fuse_unmount in the fuse.h can make the blocked fuse_main exit blocking?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.
