### ISSUE TITLE
Request: Document public changes between FUSE2 and FUSE3

### ISSUE THREAD

**Issue by billziss-gh** [libfuse/libfuse#266]
I would very much like to see documentation describing the public changes between FUSE2 and FUSE3. This is of particular interest to me because I am planning to implement the FUSE3 interface for [WinFsp](https://github.com/billziss-gh/winfsp), which currently implements only FUSE2 (high-level).

**Comment by Nikratio** [comment]
Thanks for the suggestion! The canonical list of changes is in the ChangeLog: https://github.com/libfuse/libfuse/blob/master/ChangeLog.rst#libfuse-300-2016-12-08. 

Is there something that is missing? If so, would you maybe able to compile a separate document that does a better job?

**Comment by Artoria2e5** [comment]
Bumping this up again: the many dependant, existing FSs will probably benefit from a porting guide. Even on the cutting-edge Arch Linux [a bunch of packages are stuck with fuse2](https://www.archlinux.org/packages/extra/x86_64/fuse2/) because the upstream is not porting it.

The changelog itself is quite good already, although it probably should mention these too:
* Us enabling FUSE_HANDLE_KILLPRIV means that the fs will have to do a bit extra
* The pkg-config name has been changed to fuse3 as well, so programmers should have an easy time detecting it and defining macros for `#ifdef` work (mainly for adapting to the new handler signatures.)

**Comment by probonopd** [comment]
Why is the version "3" now in 2 places in the name `libfuse3.so.3` compared to just 1 place in `libfuse.so.2`?
