### ISSUE TITLE
Support different inode number for root inode

### ISSUE THREAD

**Issue by beyondlimits** [libfuse/libfuse#267]
`fuse_lowlevel.h` contains the line:
```c
#define FUSE_ROOT_ID 1
```

The filesystem driver I want to implement uses inodes on its own, but does not guarantee the root inode will be 1. I would like the inodes to be transparent.

Also see http://fuse.996288.n3.nabble.com/Custom-value-for-FUSE-ROOT-ID-td4817.html

**Comment by Nikratio** [comment]
Thanks for the suggestion! Having this implemented might indeed be nice. But beware that there might be some pushback, since this will also require kernel changes with corresponding API version bump, all just to avoid a pretty minor fix in filesystems that need this.

Also, libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Feature requests are therefore in general unlikely to actually result in the feature being implemented.

Would you be interested in working on this? If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).
