### ISSUE TITLE
linux fuse module, cat without content

### ISSUE THREAD

**Issue by Brayden-Lee** [libfuse/libfuse#275]
I write my filesystem based on fuse, but the read function I overwritten is like this:
`int fs_read(struct fs *fs, const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fileInfo){  
int ret = 0;  
int fd;  
fd = open(path, fileInfo->flags);  
ret = pread(fd, buf, size, offset);  
if (unlikely(ret < 0)) {  
    printf("line = %d, func = %s, errno = %d, errmsg = %s\n", __LINE__, __FUNCTION__, errno,  
 strerror(errno));  
    return -EIO;  
}  
printf("read size = %d, buf = %s\n", size, buf);  
return ret;  
}`  
And I debug my file system, when I use cat example.txt to read content of the file, it return empty. but I see the log:  
`read size = 4096, buf = xxx  
read[0] 3438 bytes from 0  
unique: 12, success, outsize: 3454  
unique: 13, opcode: RELEASE (18), nodeid: 2, insize: 64, pid: 0  
release[0] flags: 0x8000  
unique: 13, success, outsize: 16`  
Why I can't input my content use cat on my fuse filesytem?  

> https://stackoverflow.com/questions/51550121/linux-fuse-module-cat-without-content

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.
