### ISSUE TITLE
Pass/Read/Write user address with cuse_lowlevel_ops.ioctl

### ISSUE THREAD

**Issue by hipersayanX** [libfuse/libfuse#280]
I'm trying to implement [v4l2_ext_controls](https://linuxtv.org/downloads/v4l-dvb-apis/uapi/v4l/vidioc-g-ext-ctrls.html#c.v4l2_ext_controls) ioctl with cuse, but _controls_ parameter need to receive and pass a pointer relative to the client calling ioctl.
Is there any way of reading/writing from that address?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.
