### ISSUE TITLE
How does one gracefully exit from cuse_lowlevel_main()

### ISSUE THREAD

**Issue by stefanberger** [libfuse/libfuse#298]
I am using cuse_lowlevel_main() to start up the CUSE operations. How do I gracefully terminate the program from within an ioctl for example? I am currently calling exit(0) (from within the ioctl processing), but would like to be able to clean up more to also quiet down valgrind.

**Comment by Nikratio** [comment]
What's wrong with `fuse_session_exit` and a global variable? 

That said, I think this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
