### ISSUE TITLE
How to use fuse for aio?

### ISSUE THREAD

**Issue by wm8120** [libfuse/libfuse#322]
AIO program uses io_getevents and io_submit system calls. But these two system calls are not in the fuse operation structure. How to implement user level logic for these two system calls?

**Comment by Nikratio** [comment]
I am actually not sure. I think it will either work out of the box (with the kernel transparently translating), or it is not supported at all. Sorry that I can't be more helpful.

(In general, please use the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker for questions like this. I'd like to reserve use of the latter to actually track issues and not use it for discussion.)
