### ISSUE TITLE
Monitoring fuse for filesystem events

### ISSUE THREAD

**Issue by DiagonalArg** [libfuse/libfuse#328]
I have a fuse filesystem that I'd like to monitor for events, as with [inotify](https://en.wikipedia.org/wiki/Inotify) or [incron](https://github.com/ar-/incron).  I am not able to set "allow_root" in fuse.conf, and I'm not sure if these tools will work even if I could.  Is there any way to monitor events that can work in user space?  (If I ran fuse as root or were able to "allow_root", any idea whether inotify/incron would work?)

**Comment by DiagonalArg** [comment]
Ok, I see inotify and incron will not work unless run by root, and in any case will not work on FUSE even if that is run under the root user.  Is there any headway with [Fsnotify and FUSE](https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE)?

**Comment by ajbouh** [comment]
I'm also interested in this! Based on my research this has been talked about by a number of people across the web but no one seems to have gotten it working. What's the latest on this front?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

**Comment by DiagonalArg** [comment]
Actually, as you see in the second post, it's a feature request regarding Fsnotify and FUSE.  It seems that two of us would be interested in the response.

**Comment by Nikratio** [comment]
As far as I know, the https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE wiki page hasn't been reviewed by libfuse committers, nor do I know of any related code. I'd suggest contacting the author directly if you'd like more information about that (stefbon@gmail.com).

With regards to feature request, my response is unfortunately always the same (so please excuse the copy & paste):

libfuse is a fully volunteer driven project[1]. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

[1] Actually, that's not strictly true. I do offer paid consulting with discounts for code that makes it into the official release. Contact me privately if that's something you'd be interested in.

**Comment by DiagonalArg** [comment]
Alright, I understand.  (Wish that I could code!)  I contacted Stef - actually had emailed him earlier.  I gather he's working on something, but there's nothing concrete yet.
