### ISSUE TITLE
Can it be implemented “writeback caching” through the high-level API ?

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#331]
Can it be implemented “writeback” through the high-level API ?

**Comment by Roay** [comment]
I added` conn->want |= FUSE_CAP_WRITEBACK_CACHE; `to the `passthrough.c` `xmp_init()` method. Then did the following

```
# gcc -Wall passthrough.c `pkg-config fuse3 --cflags --libs` -o passthrough
# ll -h passthrough
-rwxr-xr-x 1 root root 19K Nov 24 16:20 passthrough
# ./passthrough testDir/
# cd testDir/
# dd if=/dev/zero of=bigfile bs=1k seek=1024k count=1
1+0 records in
1+0 records out
1024 bytes (1.0 kB) copied, 0.000579427 s, 1.8 MB/s
# ll -h bigfile 
-rw-r--r-- 1 root root 1.1G Nov 24 16:31 bigfile
# mkfs.xfs bigfile 
# mount bigfile /mnt
# ll /mnt/
total 4
drwxr-xr-x  2 root root    6 Nov 24 17:08 ./
drwxr-xr-x 23 root root 4096 Nov 24 16:36 ../
```
A few minutes later

```
# ll /mnt/
ls: cannot access '/mnt/': Input/output error
```
How to modify the pall. C file to enable it to support the use of writeback?

**Comment by Roay** [comment]
**Can anyone answer my question? Thank you very much.**

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
