### ISSUE TITLE
mount multiple fuse instance

### ISSUE THREAD

**Issue by coderall** [libfuse/libfuse#365]
can someone help me to explain when I mount multiple fuse instances to different mounting points, how the userspace daemonize communicate with kernel FUSE module?

I have read the kernel code, and known when mounting a fuse file system, a new fuse_conn created, but multiple daemonize read the same /dev/fuse(and in fuse_dev_read it got fuse_conn from kiocb), how to distinguish the requests from the different mounting point?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
