### ISSUE TITLE
fix staged installation as nonroot

### ISSUE THREAD

**Issue by nolange** [libfuse/libfuse#387]
Installing as normal user will mean that certain privileged operation will fail.
I dont know how meson usually deals with it, but following is the patch I am using with buildroot.

```patch
diff -burN fuse-3.4.1.org/util/install_helper.sh fuse-3.4.1/util/install_helper.sh
--- fuse-3.4.1.org/util/install_helper.sh	2019-02-12 14:33:18.549507335 +0100
+++ fuse-3.4.1/util/install_helper.sh	2019-02-12 14:35:20.726772913 +0100
@@ -22,8 +22,8 @@
     DESTDIR="${DESTDIR%/}"
 fi

-chown root:root "${DESTDIR}${bindir}/fusermount3"
-chmod u+s "${DESTDIR}${bindir}/fusermount3"
+chown root:root "${DESTDIR}${bindir}/fusermount3" || :
+chmod u+s "${DESTDIR}${bindir}/fusermount3" || :

 install -D -m 644 "${MESON_SOURCE_ROOT}/util/fuse.conf" \
 	"${DESTDIR}${sysconfdir}/fuse.conf"
@@ -31,7 +31,7 @@

 if test ! -e "${DESTDIR}/dev/fuse"; then
     mkdir -p "${DESTDIR}/dev"
-    mknod "${DESTDIR}/dev/fuse" -m 0666 c 10 229
+    mknod "${DESTDIR}/dev/fuse" -m 0666 c 10 229 || :
 fi

 install -D -m 644 "${MESON_SOURCE_ROOT}/util/udev.rules" \
```

**Comment by Nikratio** [comment]
Thanks for the report! I don't think this would be a good idea to apply for everyone, because it completely swallows errors. People may forget to run as root and will think everything worked, when in fact it didn't. So I think if you want to install as non-root, it's a better choice to use the `utils` build option (which will prevent this script from running in the first place).
