### ISSUE TITLE
Callback not working in background

### ISSUE THREAD

**Issue by johnBuffer** [libfuse/libfuse#388]
Hello,

I am currently working on a filesystem using fuse and [azure-storage-cpp](https://github.com/Azure/azure-storage-cpp). The problem I have is that when I mount using the -f option, to allow fuse to run in foreground mode, everything work perfectly fine but in background it hangs forever on some azure api calls. Do you know which kind of fuse mechanisms can be the cause for this ? Can it be related to bad statics initializations from me ?
Do you think the fact that azure-storage-cpp uses async functions can be related to this ?

Thank you

**Comment by Nikratio** [comment]
I'm afraid I can't think of anything on the libfuse side that could cause this, no. Sorry...

Maybe try asking your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel)? There's more people there (and I'd like to reserve use of the issue tracker to actually track issues and not use it for discussion).

**Comment by songweijia** [comment]
Although this post is more than one year old, I still want to add something to this because going to daemon might invalidate the context by doing a lot of stuff as described [here](https://man7.org/linux/man-pages/man7/daemon.7.html). It will shift to another pid, refresh the environment variables, and etc... My suggestion to @johnBuffer is to call "fuse_daemonize()" earlier to make sure azure-storage related initialization happens in the context of daemon process.
