### ISSUE TITLE
Pass a value instead of pointer address in IOCTL

### ISSUE THREAD

**Issue by akshitkanda5** [libfuse/libfuse#414]
I am trying to pass in a value instead of a pointer in an IOCTL call
However, I don't find any suitable way to retrieve it in cuse.
Any suggestions would help
Thanks!

**Comment by akshitkanda5** [comment]
I am trying to pass in a value instead of a pointer in an IOCTL call
However, I don't find any suitable way to retrieve it in cuse.
Any suggestions would help
Thanks!

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
