### ISSUE TITLE
Performance statistics and traces in FUSE

### ISSUE THREAD

**Issue by sisgandarli** [libfuse/libfuse#431]
Hello. I am currently working on benchmarking of CernVM-FS. I need to trace and get stats of FUSE calls. I have read the [paper](https://www.usenix.org/system/files/conference/fast17/fast17-vangoor.pdf), however, I cannot find necessary information about the tools mentioned in the links at the end of the paper.

Are there ready tools for measuring performance, getting stats and tracing the FUSE calls?

Thanks,
Shahnur

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
