### ISSUE TITLE
fuse "-o auto_unmount" doesn't close fds[1] upon exiting the fuse loop

### ISSUE THREAD

**Issue by DavidButterfield** [libfuse/libfuse#432]
fuse "-o auto_unmount" doesn't close fds[1] (from the socketpair() call in
fuse_mount_fusermount) upon exiting the fuse loop.  So valgrind reports it as an
unclosed file descriptor on exit.

Perhaps more importantly, the fusermount3 process remains running with the fuse
filesystem mounted even though the fuse thread has shut down.  That situation
could remain indefinitely -- the program is not necessarily terminating just
because it ends the fuse thread. 

==26642== Open AF_UNIX socket 6: <unknown>
==26642==    at 0x4A5314A: socketpair (syscall-template.S:78)
==26642==    by 0x48E7F6E: ??? (in /lib/x86_64-linux-gnu/libfuse.so.2.9.9)
==26642==    by 0x48E8BE3: ??? (in /lib/x86_64-linux-gnu/libfuse.so.2.9.9)
==26642==    by 0x48E47D7: ??? (in /lib/x86_64-linux-gnu/libfuse.so.2.9.9)
==26642==    by 0x48E48B6: ??? (in /lib/x86_64-linux-gnu/libfuse.so.2.9.9)
==26642==    by 0x48E49EA: ??? (in /lib/x86_64-linux-gnu/libfuse.so.2.9.9)
==26642==    by 0x310262: UMC_fuse_run (UMC_fuse.c:465)
==26642==    by 0x486DE7D: sys_thread_fn (mte_service.c:145)
==26642==    by 0x491C181: start_thread (pthread_create.c:486)
==26642==    by 0x4A51B1E: clone (clone.S:95)

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by bsbernd** [comment]
I think this is already fixes by PR 1033.
