### ISSUE TITLE
cuse: 128k+ writes

### ISSUE THREAD

**Issue by kevin-gadek** [libfuse/libfuse#437]
Is there any workaround for cuse to specify a size greater than 128k for writes? Is commit 027d0d1 for max_pages support applicable to cuse as well?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
