### ISSUE TITLE
FUSE FS Variable not updating

### ISSUE THREAD

**Issue by shenoy10** [libfuse/libfuse#442]
I am currently creating a read file system using FUSE FS.

I have a char* buf =" hello world" and have implemented a read call back appropriately such that the file content is displayed when a hello_world file is read from in my system.
I call fuse_main to mount the system and the file system shows this "hello world" message as expect. However, when I attempt to make changes to buf and set it equal to "HELLO WORLD" after fuse_main is mounted, the file system continues to be displaying the previous message "hello world". Is this a bug and if not how does this issue get fixed?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
