### ISSUE TITLE
Use the fuse file system slower than xfs

### ISSUE THREAD

**Issue by suruonuo** [libfuse/libfuse#444]
I do a cmd  shell 
:  time cp  a.zip  b.zip   
In xfs
real: 0.502s
user: 0.005s
sys: 0.499s
In fuse system:
real:12.932s
user: 0.03s
sys: 4.41s
I am confuse with the results;

**Comment by suruonuo** [comment]
the size of  a.zip is 100Mb

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
