### ISSUE TITLE
How to update fusefs program when file opened on it (fd opened and writing)

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [libfuse/libfuse#446]
HI,
I write an FS base on libfuse , some app writes logs on it, and it works fine. But some times I need to update my FS program. When app writing logs use logging-framework like glog, even I umount the FS, glog interface LOG(INFO) don't get an error,APP just keep running , and when I update and remount, the app log can not write on the new FS, except to restart the app (they really don't want to do that!).

Is there any good way to solve this problem?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
