### ISSUE TITLE
“disable-mtab” is ignored

### ISSUE THREAD

**Issue by mirfatif** [libfuse/libfuse#456]
If I'm not missing something, I don't see `disable-mtab` being evaluated anywhere in the code. The only place where `IGNORE_MTAB` is defined is [lib/mount_util.c](https://github.com/libfuse/libfuse/blob/fuse-3.6.2/lib/mount_util.c#L26). But for [lib/mount.c](https://github.com/libfuse/libfuse/blob/fuse-3.6.2/lib/mount.c) and [util/fusermount.c](https://github.com/libfuse/libfuse/blob/fuse-3.6.2/util/fusermount.c) it needs to be defined explicitly e.g. in the files themselves or in `build/config.h` or in [lib/mount_util.h](https://github.com/libfuse/libfuse/blob/fuse-3.6.2/lib/mount_util.h).

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by mirfatif** [comment]
I didn't notice creating new issues isn't desired. Well, I did made necessary changes to get the required results but I would like not to take this responsibility. The reason is I don't have an educational/professional background with coding, or even computers. You may please close this as you find appropriate.

And thanks to all contributers for this great project.
