### ISSUE TITLE
Make ioctl protoype conditional on FUSE_USE_VERSION

### ISSUE THREAD

**Issue by billziss-gh** [libfuse/libfuse#463]
The `fuse_operations::ioctl` prototype was changed in #381. The original rationale appears to be in #367. This change was backwards incompatible and it produces compilation errors when building with a C++ compiler.

The following C++ code:

```C++
static fuse_operations ops =
{
    // ...
    ioctl,
};
```

Produces the following error under g++:

```
error: invalid conversion from ‘int (*)(const char*, int, void*, fuse_file_info*, unsigned int, void*)’ to ‘int (*)(const char*, unsigned int, void*, fuse_file_info*, unsigned int, void*)’ [-fpermissive]
```

Produces the following error under msvc:

```
error C2440:  'initializing': cannot convert from 'int (__cdecl *)(const char *,int,void *,fuse_file_info *,unsigned int,void *)' to 'int (__cdecl *)(const char *,unsigned int,void *,fuse_file_info *,unsigned int,void *)'
```

Please note that these are actual C++ errors and not warnings promoted to errors.

**Comment by jpandre** [comment]
What is the header of your ioctl() method ?

**Comment by billziss-gh** [comment]
> What is the header of your ioctl() method ?

```C++
static int ioctl(const char *path, int cmd, void *arg, struct fuse_file_info *fi,
        unsigned int flags, void *data);
```

**Comment by jpandre** [comment]
Try "unsigned int cmd"

**Comment by billziss-gh** [comment]
@jpandre I know how to fix the problem. That is not my point.

My point is that backwards compatibility is important and that libfuse should not be changed in a backwards incompatible manner.

**Comment by Nikratio** [comment]
My policy is that programs compiled against older versions of libfuse must still work when linked with newer libfuse versions.

I consider it acceptable to require occasional changes when *compiling* against a newer libfuse release. Whenever possible, this should be opt-in by adjusting the `FUSE_USE_VERSION` ifdef.

I am not sure if in this case this wasn't possible, or we just forgot. If there is a way to conditionally change the type depending on `FUSE_USE_VERSION`, I'd be happy to accept the patch. Otherwise, I'm afraid the cat is out of the bag - changing it back would just break compatibility again.

**Comment by billziss-gh** [comment]
> I am not sure if in this case this wasn't possible, or we just forgot. If there is a way to conditionally change the type depending on FUSE_USE_VERSION, I'd be happy to accept the patch. Otherwise, I'm afraid the cat is out of the bag - changing it back would just break compatibility again.

I would argue that by changing it back the breakage would be minimal, because the change has been out for less than a year, whereas the `ioctl` prototype has remained the same since the libfuse2 days. But your suggestion of using a `FUSE_USE_VERSION` conditional is a good compromise.

**Comment by Nikratio** [comment]
Would someone like to submit a pull request for this? Otherwise this issue will unfortunately remain unaddressed.

Libfuse does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Issues like this will therefore languish unless they come together with a  pull request.

**Comment by billziss-gh** [comment]
@nikratio I am finishing up on the winfuse kernel driver and will prepare my Windows port of libfuse for submission and review soon. I will look into this as part of that effort, although I will try to submit as separate PR.
