### ISSUE TITLE
Is there a guaranteed way to return an error from close()?

### ISSUE THREAD

**Issue by reverendhomer** [libfuse/libfuse#478]
On the one hand, FAQ and documentation clearly states that

> If you need to return errors on close, you must do that from flush()

On the other hand, [source code itself](https://github.com/libfuse/libfuse/blob/master/include/fuse_lowlevel.h#L575) states:

```
	 * Filesystems shouldn't assume that flush will always be called
	 * after some writes, or that if will be called at all.
```

In #373, @Nikratio stated:

>Under Linux, however, errors returned by FUSE's flush() handler are guaranteed to be be returned to the user in the close() return value.

Can you, please, refer to some documentation that **guarantees** that?

Thank you.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

**Comment by reverendhomer** [comment]
You can interpret this question as "you have a conflicting information in documentation". Will it look more like a bug in that case?
