### ISSUE TITLE
MMAP trouble

### ISSUE THREAD

**Issue by pglen** [libfuse/libfuse#503]
I wrote a file system, redirecting from directory to mount point. It passes all tests, excepts programs that use mmap. gcc being a prominent one that I would like to get to work in the mount directory. Any info on FUSE and MMAP together?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
