### ISSUE TITLE
How to know the requests to fuse is congested?

### ISSUE THREAD

**Issue by cheyang** [libfuse/libfuse#504]
I am new to fuse. I have 2 questions:

1. Can I only set the value of congestion_threshold itself without changing default max_background? Why congestion_threshold  should be smaller or equal max_background?

2. If the number of number of asynchronous requests in the pending and processing queues reaches the value of the tunable congestion threshold parameter, how can I know it is congested? Where to check the logging? dmesg?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
