### ISSUE TITLE
"fuse: reading device" on Ubuntu 20.04

### ISSUE THREAD

**Issue by vibhansa-msft** [libfuse/libfuse#517]
I have a libfuse based file-system running fine on Ubuntu-18.04. When I moved the same code to Ubuntu-20.04 my application is not working. On adding '-d' option to command line I see "fuse: reading device: invalid argument' error. I see on Ubuntu-20 libfuse version is 2.9.9 while on Ubuntu 18.04 its 2.9.7. Is there any thing application needs to change to be compatible with 2.9.9. I tried to debug this and seems while reading from /dev/fuse/ libfuse is encountering some error and then it  start the destroy sequence.

**Comment by vibhansa-msft** [comment]
Tried to integrate with fuse3 and still see the same behaviour.

**Comment by vibhansa-msft** [comment]
Can someone help me with this, I am still unable to figure out why its failing with 2.9.9 version.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
