### ISSUE TITLE
fuse version 4 ideas and discussion: pure userspace private virtual mounts

### ISSUE THREAD

**Issue by KOLANICH** [libfuse/libfuse#554]
Fuse is a very nice thing, but it has some drawbacks.

Let's imagine there is an app. And there are some already implemented fuse FSes. And the app has to deal with the stuff. One of the low-hanging fruits is to reuse the impls in the FSes. But currently

1. It requires managing a child process. I mean tracking if it has crashed for example, and doing restart routine.
2. It requires a mount point and proper unmounting of the mounted resource. If parent crashes, what will unmount the FS and delete the mount point? Also the mount point is on disk, so can wear flash memory in the most of cases. 
3. Accesses still go through kernel.

Hand-managing other processes is always a pain. Though it can be automated to some extent, the proper solutikn requires a bit of redesign.

But mainly FUSe is just an interface. And most of the fuse programs have to be structured the very similar way.

So the proposal is
1. allow to define FUSE v4 FSes as shared libraries, loaded by `fusermount` and implementing a certain interface.
2. prescribe to implement the new code this way.
3. since executables can be used as shared libs, it is possible to use both ways in the same binary
4. implement a client library. The client library should implement the code hooking the standard library in the process it is called in to allow to reroute the calls through fuse server. So, calls through fuse don't go through kernel (which sometimes cause very nasty bug with unkillable processes and unmountable FSes, and unshutdownable system), when it is not needed, so it gonna be fast. But it will impose some small overhead on regular calls.

The proposed approach is following:
1. user loads the client lib and calls it init routine. The init routine creates a memory struct for filters. Likely a hashtable.
2. the client lib hooks the stdlib adding to the stdlib funcs a stub, checking if the file name matches a certain pattern, and then checking the table of filters
3. a user registers filters by chosing aliases for them from the set of characters not valid for file paths and mapping them to fuse server libs and their startup params.
4. when a user opens the first file for a filter, the fuse client lib loads the server lib, initializes and registers it
5. file accesses are processed within server lib without routing through kernel.

**Comment by fsgeek** [comment]
I've been exploring issues in the space off and on for the past several years.  What I have right now is somewhat similar to what you're describing: an LD_PRELOAD library that catches calls into glibc and then sends messages to a modified version of the FUSE file system library.   Within the FUSE library, I have two sources of messages: the kernel, and messages from the client application(s).  Because I want to allow kernel mode fallback, I have some additional overhead in the open path, where I directly check if the file exists and if it does, returning a handle and associating the file descriptor and handle together in a table.  Calls that take a name bypass this because I can send the request directly to the FUSE library.

The library side code then translates the message into calls for the original FUSE file system.  There's a bit of complexity here because the moment you bypass the kernel, you have to implement some of that functionality.  For example, path names need to be split apart.  Some FUSE file systems can handle full paths (e.g., passthrough_ll) but there's no requirement the file system be able to handle path parsing. 

There is potentially some complex state management for this hybrid model: the fact that the file pointer is maintained in the kernel, for example, means that even if you implement the read/write calls via message passing, you have to call the kernel to update the file pointer. 

My original motivation for this was not performance, but rather extensibility: my research is in rich graph structured name spaces, I don't know what the interfaces are going to look like.  So I wanted a flexible way of adding such functionality.  

For example, one of the things I did is a remote side search mechanisms where, given a list of names and a list of locations, return the first instance of the name in the list of locations. This can speed up things like program load, compilation, etc., where those searches are done brute-force.  Gcc, for example, does build a cache, but each new invocation has to re-do it.  What I found was that doing the search in the FUSE library took 20% of the time of doing it the traditional way (using stat calls).

Part of my motivation for this is the work by Vangoor and Zadok (https://www.usenix.org/system/files/conference/fast17/fast17-vangoor.pdf) where they indicates that the overhead for meta-data operations was a substantial bottleneck.   The ExtFuse work (https://www.usenix.org/system/files/atc19-bijlani.pdf) focuses on improving I/O performance with kernel extensions, though one question I had is how much speedup would be achieved by bumping up the current FUSE limit (128KB as I recall) for an I/O operation to something reasonable for 64 bit systems (2 GB, perhaps?)   I've started implementing a shared memory mechanism, so read/write can be directly sent to the remote file system with a single data copy, but that will cause a loss of the buffer caching within the kernel layer.

Of course, right now, my goal is to demonstrate the practicality of this approach.  I had performance numbers in July that suggested I was running faster through my system than I was able to do with native ext4 on NVMe, which was encouraging.  To do this, I built a FUSE file system that doesn't have any storage and just maintains a namespace with memory mapped files for data storage.  I don't care about persistence and my goal was to minimize the overhead in the FUSE library + file system layer (and indeed, nothing in either of those show up in perf, when I run various tests, with the bulk of the overhead in the system call handling between kernel and application).

You can see what I've been doing here: https://github.com/fsgeek/finesse

With respect to your specific proposal:

1. allow to define FUSE v4 FSes as shared libraries, loaded by fusermount and implementing a certain interface.

You'd be doing this per user, correct?  Otherwise, you have the usual multi-tenancy issues to deal with.

I don't see any reason why you couldn't convert the model from binding FUSE as the shared library to loading the file system as the shared library.  Presumably, the interface would be done via the load initialization mechanism shared libraries use, where it can then register its callbacks.  That would preserve the existing model fairly closely and minimize necessary changes.

One thing to consider is how you would pass configuration options via this model, since they aren't going to be passed on the command line any longer.

2. prescribe to implement the new code this way.

If you want adoption, you need to make this as transparent/minimal as possible.  Indeed, I suspect you could do this in a way that is compatible with the existing mechanism, just a different implementation of the callback registration.

3. since executables can be used as shared libs, it is possible to use both ways in the same binary

What is your goal here?  To allow the FUSE file system to work the way it does now?  Perhaps this is one way of passing configuration options into the request to load the FUSE file system as a library.

4. implement a client library. The client library should implement the code hooking the standard library in the process it is called in to allow to reroute the calls through fuse server. So, calls through fuse don't go through kernel (which sometimes cause very nasty bug with unkillable processes and unmountable FSes, and unshutdownable system), when it is not needed, so it gonna be fast. But it will impose some small overhead on regular calls.

This is where things get tricky.  Some programs won't allow you to use LD_PRELOAD (e.g., anything running with uid 0).  You can't capture all calls.  Glibc at least does complex name substitution.   The **at** variants of calls are becoming increasingly popular and that starts to add overhead as well because now you have to retrieve the current working directory and adjust names.  Some things just won't work right (e.g., symbolic links) so you have to think about how you'll handle those cases: failures that are due to limitations in what you can do.

In fact, I think that if this approach is to be more generally useful, it should be integrated into libc, which would make it more generally useful.

My own work suggests that there are considerable benefits to bypassing the kernel here: it eliminates the heavy-weight path from application  into the kernel, through VFS, fuse kernel, and fuse library.  With the slowdown in system calls due to the past few years of side channel attacks, eliminating extra system calls is definitely a win, as is adding any data copy.

Something else you might want to consider is that if the FUSE file system is a shared library, you could also just invoke it directly from a single application.  That would yield optimal performance for a single application (e.g., an HPC application) while leveraging the plethora of FUSE file systems that are out there.

**Comment by KOLANICH** [comment]
>You'd be doing this per user, correct? Otherwise, you have the usual multi-tenancy issues to deal with.

In fact I haven't considered multitenancy at all. The key idea in the first point is that instead of defining the required functions within an app and then passing them as a structure into a fuse lib, we define the required functions within a lib, export them, and everyone else can pass them to fuse.

>  Presumably, the interface would be done via the load initialization mechanism shared libraries use

Not quite. For example in Windows one is not allowed to call anything from other shared libraries in DllMain and funcs called from it.

So, initialization code should be exported as a function.

>One thing to consider is how you would pass configuration options via this model, since they aren't going to be passed on the command line any longer.

The options can be passed to the function mentioned. Though IMHO instead of argc, argv new interface should be more object oriented. I mean one doesn't want to construct a text string only to have it parsed by fuse server. It is a bit inconvenient.

>What is your goal here? To allow the FUSE file system to work the way it does nowv

To allow fs authors to allow people not to change their code and their habits.

> Some programs won't allow you to use LD_PRELOAD

No LD_PRELOAD, the decision is taken within the app, so we cannot rely on LD_PRELOAD. Instead it is proposed to just use splicing or tables patching.

>Something else you might want to consider is that if the FUSE file system is a shared library, you could also just invoke it directly from a single application.

The idea was to do exactly this, but moving the shared code into the `fuse client library`. So we just import a client library and register servers used, and then just use them by prepending file names with them. What is important here:

1. we hook the stdlib. So other shared libs using the funcs from the same stdlib also get additional features. So, for example, we can import the fuse client lib into python using ctypes, call the init function, register servers, and then magically every other native libs loaded into python interpreter, and the interpreter itself, can use the registered prefixes. Almost no modifications in code are needed, except the one allowing python interpreter and `pathlib` pass incorrect paths.

2. We don't do the work by hooking and bookkeeping ourself, it is fuse client library does it.

3. `*at` functions is a good thing, but other libs not using them should also get the benefits, so we use prefixes. There is some overhead in constructing them, but we really have no other choice, if we want to support non-`at`ed functions too.

**Comment by Nikratio** [comment]
Thank you for the reporting this idea! I think it is an interesting one that deserves further discussion (which I see has already started happening). I don't think the FUSE bugtracker is the right venue for this though.

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. The purpose of the issue tracker, however,  is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done.

I'll therefore close this issue for now, but I'd encourage you to continue the discussion on e.g. the libfuse mailing list. Once there is code that implements the functionality, you're very welcome to move back to the issue tracker / pull request.
