### ISSUE TITLE
Case insensitive file system (Lookup problem)

### ISSUE THREAD

**Issue by 14Merlin** [libfuse/libfuse#561]
Hi,
I'm developing a fuse module in which I have a case insensitive file system. In particular it is all UPPERCASE.
I'm doing just basic operations: open, write, read, delete, listdir.
For almost all operations I can convert to uppercase the "const char* path" parameter before doing everything else.

I'm using basic API (not lowlevel)

All works except when issuing "ls" command with wildcards. For example if I issue "ls *.txt" it doesn't work because LOOKUP doesn't find any .txt files. (Obviously if I issue "ls *.TXT" is does work without problems)

At this point I'm trying to figure out how to alter path name (just making it uppercase) to the LOOKUP function but I found that to do I need the lowlevel api.
I tried to look at lowlevel api but I cannot exactly know how to alter original lookup function just making the path uppercase.

Anyone could help me? 
Many thanks!

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
