### ISSUE TITLE
get_attr() keeps on getting info of root dir

### ISSUE THREAD

**Issue by T1anZhenYu** [libfuse/libfuse#563]
I develop some basic filesystem operations using fuse such as write, read, and they work fine. But I found fuse keeps on invoking get_attr() about once a second to get the root info. How can I stop it?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
