### ISSUE TITLE
readdir returns d_ino==-1 in offset==0 mode

### ISSUE THREAD

**Issue by mpartel** [libfuse/libfuse#583]
(Background: @McBane87 and I are trying to [upgrade](https://github.com/mpartel/bindfs/pull/95) [bindfs](https://bindfs.org/) to FUSE 3.)

Always passing 0 as the offset to the readdir filler function ("mode 1" in `fuse.h`) causes clients to always see `d_ino == -1` when they readdir ([test program](https://github.com/mpartel/bindfs/blob/master/tests/readdir_inode.c)).

- The `passthrough` example exhibits this problem, but `passthrough_fh` and `passthrough_ll` don't.
- `use_ino` is set.
- It doesn't matter whether `FUSE_FILL_DIR_PLUS` is passed.

### Possible fix

On [this line](https://github.com/libfuse/libfuse/blob/b9e3ea01dbbbba9518da216dd29c042af871ae31/lib/fuse.c#L3569), remove `off && `.

Then `passthrough` passes through inode numbers if I just change it to (always) pass `FUSE_FILL_DIR_PLUS`.

I don't know the code well enough to tell whether that change is safe. It doesn't break any tests at least.

**Comment by Nikratio** [comment]
Thanks for the report!

Looks this check has been there ever since the first introduction of readdirplus support in 2014.

Looking at the code, I am not sure why there is a condition on `off` here. On the other hand, I also do not see how always passing 0 is expected to work. If you look further down, then setting `off == 0` bypasses all sorts of buffer extension logic. I think the check on `off` is meant to check if this is the first call to the function, and calling the function repeatedly with `off==0` means things will not work right.

**Comment by mpartel** [comment]
`off == 0` is documented [here](https://github.com/libfuse/libfuse/blob/b9e3ea01dbbbba9518da216dd29c042af871ae31/include/fuse.h#L545) and [this codepath](https://github.com/libfuse/libfuse/blob/b9e3ea01dbbbba9518da216dd29c042af871ae31/lib/fuse.c#L3609) seems to handle it correctly, by adding the entry to a linked list, which is later [copied into the buffer](https://github.com/libfuse/libfuse/blob/master/lib/fuse.c#L3737). Also [this](https://github.com/libfuse/libfuse/blob/master/example/passthrough_fh.c#L191) is in agreement with the documentation that `off` should not be 0 even in the first call if the 2nd mode is desired.

The first if-else in `fill_dir_plus` seems entirely unrelated to the filling strategy. It doesn't even pass `dh` anywhere. So I'm pretty convinced now that the `off` check can be removed.

**Comment by Nikratio** [comment]
Makes sense - pull requests welcome :-). This would be a great opportunity to add a unit test for this mode of operation, so that it doesn't break again in the future.

**Comment by jpandre** [comment]
I seem to have fallen in the same trap under the same conditions.
But IMHO the fix is only partial : the st_mode is not set, which causes the d_type not to be returned in readdir().

Moreover, the st_ino is not taken from the "struct stat" provided by the filler when use_ino is set, resulting of d_ino returned as -1.

The patch below fixes that, but the conditions might not be correct, maybe st_mode should be filled unconditionally.

 --- a/lib/fuse.c	2021-03-02 21:40:51.112958271 +0100
+++ b/lib/fuse.c	2021-03-04 15:50:52.294095236 +0100
@@ -3576,6 +3576,8 @@
 				return 1;
 			}
 		}
+	} else if (statp && f->conf.use_ino) {
+		e.attr = *statp;
 	} else {
 		e.attr.st_ino = FUSE_UNKNOWN_INO;
 		if (!f->conf.use_ino && f->conf.readdir_ino) {

**Comment by jpandre** [comment]
The same patch again with proper fencing. Sorry about it.
```
--- a/lib/fuse.c	2021-03-02 21:40:51.112958271 +0100
+++ b/lib/fuse.c	2021-03-04 15:50:52.294095236 +0100
@@ -3576,6 +3576,8 @@
 				return 1;
 			}
 		}
+	} else if (statp && f->conf.use_ino) {
+		e.attr = *statp;
 	} else {
 		e.attr.st_ino = FUSE_UNKNOWN_INO;
 		if (!f->conf.use_ino && f->conf.readdir_ino) {
```
