### ISSUE TITLE
libfuse can't work with libevent

### ISSUE THREAD

**Issue by h1467792822** [libfuse/libfuse#59]
Hi,
libfuse provided an API of fuse_chan_fd to access the field of "fd" defined in fuse_chan, based on fuse_chan_fd, libfuse can work with libevent well, but in the latest codes, the API, fuse_chan_fd, has been removed. 

Thanks
hunting

**Comment by Nikratio** [comment]
Thanks for the report! Do you know of existing file systems that use this feature? If so, could you provide some links?

**Comment by Nikratio** [comment]
As far as I can tell, the channel interface serves no real function, because there is always exactly one channel associated with one fuse session. So it just adds a pointless layer of redirection. However, I see no reason why we couldn't instead expose the fd with a new function, say `fuse_session_fd(struct fuse_session *s)`.

**Comment by mrvn** [comment]
I can't give you a known filesystem that uses it but my fuse bindings for ocaml certainly use it to work with linux libaio for asynchron IO. Any filesystem using a library with event loop needs the FD. But a fuse_session_fd() works just fine there. But why not have the old function call return the common FD?

**Comment by Nikratio** [comment]
`fuse_chan_fd` accepts a `struct fuse_chan` parameter. There is no more `struct fuse_chan`. Yes, it could be preserved for backwards compatibility, but one of the main reasons for having a FUSE 3.x is to get rid of all the backwards-compatibility cruft.
