### ISSUE TITLE
can't find libfuse during compile

### ISSUE THREAD

**Issue by henr2011** [libfuse/libfuse#594]
Trying to compile Veracrypt for RPi 64bit, fails can't find fuse:

Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
Compiling FuseService.cpp
FuseService.cpp:16:10: fatal error: fuse3.h: No such file or directory
 #include <fuse3.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [/home/shared/work/build/VeraCrypt_1.23_Source/src/Build/Include/Makefile.inc:25: FuseService.o] Error 1
make: *** [Makefile:391: all] Error 2
I have tried setting PKG_CONFIG_PATH and LIBFUSE_PATH, and 2 different versions of libfuse but get the same error every time.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
