### ISSUE TITLE
FUSE function name in new fuse API 

### ISSUE THREAD

**Issue by Gorparth** [libfuse/libfuse#595]
which function is similar to FUSE in new api can anyone please tell ?
which takes mountpoint etc as parameters? and and what should we replace in new api for LoggingMixIn, Operations and 
FuseOSError??

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
