### ISSUE TITLE
Implemenation of Write and Create fucntion?

### ISSUE THREAD

**Issue by Gorparth** [libfuse/libfuse#605]
I'm implementing google-drive-fs and in that I've completed readdir,read,getattr,etc functions but I'm stuck at write function,
I want to know what are call sequence when write function is usually called , I've implemented write function but it is not getting called only, Is there any other need for write, I've searched a bit on net and tries to implement flush,release,truncate but none of the function is executed.

What I'm implementing in write is,
- getting file-id
- opening temporary file and writing previous file content (before new write)
- then writing new data coming from buffer (with write function)
- Uploading it back to the cloud

If possible please explain release,truncate and flush functions in brief.
I've not implemented file handler and caching but the functions work properly except this write.
and i want to know about create function too, can you provide the same thing for create function. i guess there are some relation between this write and create function. what is the sequence of function calls after/before create function and same for write function?

Thank you.

Attaching files with it, mailed you to but blocked by gmail
[GDriveFS.zip](https://github.com/libfuse/libfuse/files/6467104/GDriveFS.zip)

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
