### ISSUE TITLE
Attaching new mount to running fuse module

### ISSUE THREAD

**Issue by jblomer** [libfuse/libfuse#617]
I am wondering if there is a way to "attach" a new mount to an existing fuse module. Let's say `/foo/bar` is a fuse mountpoint that mounted the virtual device "bar". Then we have another mount request for `/other/bar` with the same virtual device "bar". Would it be possible to let the already existing fuse daemon also serve this new mount point, instead of creating a new fuse daemon?

The background for this question is occasional problems we see with [our fuse filesystem](https://github.com/cvmfs/cvmfs) and mount namespaces. On a usual client, we have system-wide, autofs managed mountpoints.  When a new mount namespace is created (which can be done unprivileged in combination with user namespaces), it can happen that a mountpoint is used inside the new namespace but idle in the root mount namespace.  So autofs unmounts the parent, system-wide mountpoint.  But the fuse module stays active and still serves mountpoint in the child mount namespace. Because the fuse daemon also blocks other system-wide resources corresponding to the mountpoint, this situation effectively prevents new mounts until the child mount namespaces closes.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
