### ISSUE TITLE
When I ls the dir in the mount point, there are many unknown paths to lookup.

### ISSUE THREAD

**Issue by ugiwgh** [libfuse/libfuse#618]
I print the log in hello_getattr(). And the log as following.

hello_getattr path=/ls
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libselinux.so.1
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libcap.so.2
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libacl.so.1
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libc.so.6
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libpcre.so.1
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libdl.so.2
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libattr.so.1
hello_getattr path=/tls
hello_getattr path=/tls
hello_getattr path=/x86_64
hello_getattr path=/libpthread.so.0
hello_readdir path=/

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
