### ISSUE TITLE
Option to prevent changing pthread cancellation 

### ISSUE THREAD

**Issue by chris-laplante** [libfuse/libfuse#645]
I'd like to re-hash an issue I first reported in 2019 [on SourceForge](https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/MW2PR12MB2540B6C2056FC33E2C01B4E88B140%40MW2PR12MB2540.namprd12.prod.outlook.com/#msg36684905). I ran into it again and I'd like to volunteer to fix it. As a reminder, the basic issue is that in fuse_loop_mt.c the `fuse_do_work` method makes some assumptions about the usage of pthread cancel state that are not necessarily true. Specifically, it assumes that the user wants cancelation disabled except when calling `fuse_session_receive_buf_int`:

lines 125-127:
```
pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
res = fuse_session_receive_buf_int(mt->se, &w->fbuf, w->ch);
pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
```

At the time, in 2019, we decided that the solution would be to create some kind of per-thread initialization callback. Looking back on that decision, I'm not sure it would fix the issue unless we had two callbacks: one that is executed before the `fuse_session_receive_buf_int` and one that is executed after.

I do still think that the per-thread init callback is a good idea for other reasons. The main one I had in mind in 2019 was to be able to set worker thread names. But, I don't think it's the right solution here. 

I would like re-propose the idea to add a mount flag to manage pthread cancel. To maintain backwards compatibility the default setting would not change the existing behavior. But an option would be exposed to skip the calls to `pthread_setcancelstate`.

**Comment by Smit-tay** [comment]
Looking at this issue, it seems to me that this code is already wrong, and should look more like:

```
int oldstate;
pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldstate);
res = fuse_session_receive_buf_int(mt->se, &w->fbuf, w->ch);
pthread_setcancelstate(oldstate, NULL);
```

**Comment by chris-laplante** [comment]
> Looking at this issue, it seems to me that this code is already wrong, and should look more like:
> 
> ```
> int oldstate;
> pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldstate);
> res = fuse_session_receive_buf_int(mt->se, &w->fbuf, w->ch);
> pthread_setcancelstate(oldstate, NULL);
> ```

Yes, I agree. However at this point, I'm concerned that many filesystems out there have been unwittingly designed with pthread cancelation always off, so this would change their behavior. Though maybe it is enough to say: "If you want the previous behavior, make sure you explicitly call `pthread_setcancelstate(PTHREAD_CANCEL_DISABLE)`" in your setup code?

**Comment by aakefbs** [comment]
Maybe you could fill in here what you are trying to achieve? fuse_session_receive_buf_int() does a read() or splice() system call on the /dev/fuse file descriptor and unless that descriptor got set to non-blocking it will just wait in the kernel. In kernel fuse knows how to wake up the threads on fuser-userspace termination - I'm not sure what the pthread-cancel here is about at all.

**Comment by chris-laplante** [comment]
> Maybe you could fill in here what you are trying to achieve? fuse_session_receive_buf_int() does a read() or splice() system call on the /dev/fuse file descriptor and unless that descriptor got set to non-blocking it will just wait in the kernel. In kernel fuse knows how to wake up the threads on fuser-userspace termination - I'm not sure what the pthread-cancel here is about at all.

All I want to achieve is to stop libfuse from messing around with pthread cancel state. More specifically, basically https://github.com/libfuse/libfuse/issues/645#issuecomment-1055211406

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.
