### ISSUE TITLE
fusermount: accept x-* mount options

### ISSUE THREAD

**Issue by cpatulea** [libfuse/libfuse#651]
Hello, I have noticed that gvfsd-trash is very "nosey" and polls mount points for some of its special directories. When running fuse with "-d" (debug):

```
unique: 14, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 4752
LOOKUP /.Trash
unique: 20, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 4752
LOOKUP /.Trash
unique: 26, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 4752
LOOKUP /.Trash
```

This creates a lot of noise.

The polls can be disabled with an option "x-gvfs-notrash": https://gitlab.gnome.org/GNOME/gvfs/-/blob/master/daemon/trashlib/trashwatcher.c#L234

mount(8) defines these options as follows:

X-*
           All options prefixed with "X-" are interpreted as comments or
           as userspace application-specific options. These options are
           not stored in user space (e.g., mtab file), nor sent to the
           mount.type helpers nor to the [mount(2)](https://man7.org/linux/man-pages/man2/mount.2.html) system call. The
           suggested format is X-appname.option.

x-*
           The same as X-* options, but stored permanently in user
           space. This means the options are also available for
           [umount(8)](https://man7.org/linux/man-pages/man8/umount.8.html) or other operations.

Would it be possible for fusermount to support these?

I think the only change needed would be: Make fusermount.c's do_mount ignore these options. They should not be passed to mount() syscall. Later fusermount will pass them to add_mount for adding to mtab, which is where other programs will look for them.

Thanks in advance!

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.
