### ISSUE TITLE
Enable `FUSE_CAP_CACHE_SYMLINK` by default

### ISSUE THREAD

**Issue by mharvey-jt** [libfuse/libfuse#669]
`libfuse` 3.10 nominally has support for this feature but it is disabled by default, and there's no fuse option for enabling it.

Any reason not to enable this by default for kernels which support it?  This can be done with

```
	LL_SET_DEFAULT(1, FUSE_CAP_CACHE_SYMLINKS);
```
at https://github.com/libfuse/libfuse/blob/96ad05c8e12bae3c53401d4a856c168ef6c04345/lib/fuse_lowlevel.c#L2030 

Adding a mount option for explicitly setting disabling it would also be useful.

**Comment by Nikratio** [comment]
Pull requests for adding support are welcome :-).

When it comes to making this the default I'm more skeptical because of backwards compatibility. What does this feature do, exactly?

**Comment by mharvey-jt** [comment]
Sure, I can work something up.
With this capability enabled the kernel will cache the dereferenced value of a symlink (for the attribute cache ttl). Otherwise every dereference is referred on to the fuse server process.
Seems like a reasonable feature to enable by default, much as other caching is (perhaps bumping the minor version to indicate a change in behaviour).

**Comment by trapexit** [comment]
Why should libfuse set the value of anything? One major issue with libfuse in the past was that it provided argument parsing and was used by most every project that leveraged libfuse resulting in users being able to set things that shouldn't have been changeable but due to the way libfuse was designed was more work to disable access and so just weren't. Caching, even symlink caching, requires certain assumptions to be known and held by the filesystem. If the filesystem doesn't know caching is one and actively expire nodes (not uncommon) then enabling caching could lead to stale data or states.

**Comment by mharvey-jt** [comment]
fair enough, I see that it can be set programmatically in the `.init()` callback.
