### ISSUE TITLE
3.11.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [libfuse/libfuse#675]
Looks lik etrst suite is failing
```console
+ cd libfuse-fuse-3.11.0
+ /usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.11.0/x86_64-redhat-linux-gnu'
ninja: no work to do.
1/1 wrong_command        FAIL            0.01s   exit status 1
>>> MALLOC_PERTURB_=9 /home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.11.0/x86_64-redhat-linux-gnu/test/wrong_command
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stderr:
This is not the command you are looking for.
You probably want to run 'python3 -m pytest test/' instead
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

1/1 wrong_command FAIL            0.01s   exit status 1


Ok:                 0
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.11.0/x86_64-redhat-linux-gnu/meson-logs/testlog.txt
```
BTW using `python3 -m pytes` is not correct way of using pytest because when it is executed `python -m <foo>` pyton automatically adds curretn directory to `sys.path`.
This is why pytest provides `pytest` script.

**Comment by eli-schwartz** [comment]
https://github.com/libfuse/libfuse/blob/bdd2d4110fbc6d2059eb699efad2cca4a7eacccb/test/util.py#L128-L129

**Comment by kloczek** [comment]
I'm running my builds inside LXC zones where there is no that dev (by default).
Looks like message is misleading because it is not about lack of loaded fuse module but missing /dev/fuse and that check is not checking loaded module.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.

**Comment by kloczek** [comment]
I understand.
What could be usefull would be some suggestions what exactly I can try do to diagnose that 🤔 
Do you have any suggestions?

**Comment by eli-schwartz** [comment]
> In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

In a situation like this, using tags could possibly help, While I don't think github has the ability to set a sensible default view other than "all open issues", it might be useful to create some tag to indicate "closed issues that aren't resolved, but are just extremely low-priority wishlist items".
