### ISSUE TITLE
Does libfuse 3.x support statx syscall?

### ISSUE THREAD

**Issue by daleydeng** [libfuse/libfuse#676]

**Comment by trapexit** [comment]
No. Technically 'stat' itself isn't "supported". The FUSE request that is related is FUSE_GETATTR.

https://github.com/libfuse/libfuse/blob/master/include/fuse_kernel.h#L393

What exactly are you looking for? btime?

**Comment by daleydeng** [comment]
Maybe I'm using it in a wrong case. I treat a regular file as mounting point instead of directory, fuse cant do this, is it right? @trapexit

**Comment by daleydeng** [comment]
New binary /usr/bin/ls in fedora35 is using statx as underline syscall, which can't work with fuse.
![image](https://user-images.githubusercontent.com/770506/167054555-03006a5a-414a-471b-bc58-dd073e8f9239.png)

**Comment by trapexit** [comment]
Not sure what you mean exactly. A mount point must be a directory. That has nothing to do with FUSE.

**Comment by Nikratio** [comment]
I'm pretty sure that a mount point can be a file, and that FUSE supports this. Not sure how this is related to `statx` though.

In any case, as far as I can tell, this is a question about how to use fuse rather than a bug report. Please continue tho discussion on the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

**Comment by trapexit** [comment]
Or https://github.com/libfuse/libfuse/discussions
