### ISSUE TITLE
Set fuse_session_mount use atime no relatime

### ISSUE THREAD

**Issue by fansehep** [libfuse/libfuse#694]
Hello, libfuse members!
I have meet a problem is :
![2022-08-22_20-08-1661172950](https://user-images.githubusercontent.com/75058860/185926907-7217d600-0b78-4906-98fa-0cc7cbc6d7c3.jpg)
here the mount disk configopt is relatime.
I want to know how can i set the moutopt to use atime?

Maybe this issue being a discussions is good. but there a bro's questions nobody answer him in GitHub's Discussions.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
