### ISSUE TITLE
Fuse support problem

### ISSUE THREAD

**Issue by rongliangtang** [libfuse/libfuse#702]
Hi, your project is so great. I don't know whether it supports ios. if fuse isn't support ios, could you tell me there are any similar project support ios.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
