### ISSUE TITLE
Possible infinite recursion

### ISSUE THREAD

**Issue by Vadiml1024** [libfuse/libfuse#709]
https://github.com/libfuse/libfuse/blob/085cbab117b72df8da113a46d9ec9ba64ca301c6/example/passthrough_fh.c#L116

I wonder how does infinite recursion in this (and others) methods is avoided

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.
