### ISSUE TITLE
Clarification: fuse_file_info struct pointer (null) value in read/write calls

### ISSUE THREAD

**Issue by xander-hirsch** [libfuse/libfuse#712]
The [`passthrough.c`](https://github.com/libfuse/libfuse/blob/09862556887caf32b37aa0caa412c467f7f5a40e/example/passthrough.c) examples test if the `fuse_file_info` argument to any off `xmp_read()`, `xmp_write()`, and `xmp_fallocate()` could be `NULL`. Are there circumstances where the `fuse_file_info` argument to any of these functions would be `NULL`? The [documentation](https://github.com/libfuse/libfuse/blob/09862556887caf32b37aa0caa412c467f7f5a40e/include/fuse.h) is clear that `chown()`, `chmod()`, etc may receive a `NULL` value for `fuse_file_info`; however, there is no similar mention for `read()` and `write()`.

https://github.com/libfuse/libfuse/blob/09862556887caf32b37aa0caa412c467f7f5a40e/example/passthrough.c#L293-L302

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
