### ISSUE TITLE
Race condition with default_permissions

### ISSUE THREAD

**Issue by mpartel** [libfuse/libfuse#733]
bindfs got a [bug report](https://github.com/mpartel/bindfs/issues/120) about random EACCES errors under non-trivial load, when using the option to show files as owned by whoever is looking.

I repro'd it with a minimally modified `example/passthrough.c`. I added the following line to `xmp_getattr`:
```c
stbuf->st_uid = fuse_get_context()->uid;
```

Then the issue can be triggered by running `passthrough -oallow_other -odefault_permissions ...` and subjecting it to lots of `stat` requests by user 1 on a directory where user 2 tries to create or delete files.

As far as I can tell, both `bindfs` and `passthrough` ask FUSE to disable all attribute caching.

**Script to trigger the issue**: https://github.com/mpartel/bug-report--fuse-permission-bug (`./test.sh another-user`)
The script is non-deterministic and **does not trigger the issue on all machines**. On others it triggers it in a few seconds.

It works reliably on my (extremely slow) AMD GX-412TC but not at all on my Ryzen 5900X. @wentam also reported it working on an i5-7300U and some others.

This issue happens on a variety of distros and kernel versions:
- Debian 11 with the latest libfuse3 from git, as well as with the distro's stock libfuse3.
- @wentam reported seeing this with both FUSE 2 and 3 on NixOS, as well as with kernel 6.1.9.
- The Ryzen can't repro the issue even in a VM running the same OS as the GX, so it's very likely some kind of timing issue, not a software version issue.

**Comment by mpartel** [comment]
> Why do you believe this is a bug though?

In my perhaps naive view, FUSE should always ask the filesystem for the attributes it uses for each `default_permissions` check. It should never reuse the result if attribute caching is disabled. So if two different proceses try to operate on the file in parallel, two separate access checks should always occur.


> In Linux every inode needs to have exactly one set of file file attributes. It can't have one set of attributes for one process and, at the same time, another set of attributes to a different process.

If this means that Linux effectively always caches the inode's permissions internally for a very short time, and if there's no easy way around that, then I guess all we can do is document this behaviour for `getattr` and perhaps `default_permissions`.


> The same thing can be seen on any other file system, not necessarily FUSE-based one, by running this Python 3 script as root: [..]

This looks different: you permanently chown the file away from the creator. This failing matches my expectations.

**Comment by marcinsulikowski** [comment]
After having a closer look at this, I can see that the FUSE kernel module generally tries to do what you say – `attr_timeout` of `0` is a special case in [this code in fs/fuse/dir.c](https://github.com/torvalds/linux/blob/v6.1/fs/fuse/dir.c#L97):
```c
/*
 * Calculate the time in jiffies until a dentry/attributes are valid
 */
static u64 time_to_jiffies(u64 sec, u32 nsec)
{
	if (sec || nsec) {
		struct timespec64 ts = {
			sec,
			min_t(u32, nsec, NSEC_PER_SEC - 1)
		};

		return get_jiffies_64() + timespec64_to_jiffies(&ts);
	} else
		return 0;
}
```
The function returns `0` when attr timeout is 0, and 0 is time in jiffies which is always in the past. Setting the validity deadline of attributes in the past means the attributes can never be reused by the kernel. On top of that, there's [special code in fuse_permission()](https://github.com/torvalds/linux/blob/v6.1/fs/fuse/dir.c#L1359) which forces refreshing file attributes every time FUSE would return `EACCES` even if the cached attributes did not expire yet.

So theoretically we should be good. Despite systems calls from different processes operate on the same `struct inode*` when accessing the same file, `fuse_permission()` should always update that `struct inode*`'s attributes using fresh data from user space before checking access. But then there's a question what happens when two `fuse_permission()` are running in parallel and I think we may be in trouble here.

Syscalls like `utimensat` acquire an exclusive lock on a given inode; see [vfs_utimes](https://github.com/torvalds/linux/blob/v6.1/fs/utimes.c#L64) (`inode_lock(inode)` is an excluding lock; `inode_lock_shared(inode)` would be a shared lock). This means that while `utimensat` is executing, no other parallel system call should be changing `struct inode*` it operates on between the two lines of code I marked here:

```c
static int fuse_permission(struct user_namespace *mnt_userns,
			   struct inode *inode, int mask)
{
	(...)
	/*
	 * If attributes are needed, refresh them before proceeding
	 */
	if (fc->default_permissions ||
	    ((mask & MAY_EXEC) && S_ISREG(inode->i_mode))) {
		struct fuse_inode *fi = get_fuse_inode(inode);
		u32 perm_mask = STATX_MODE | STATX_UID | STATX_GID;

		if (perm_mask & READ_ONCE(fi->inval_mask) ||
		    time_before64(fi->i_time, get_jiffies_64())) {
			refreshed = true;

			err = fuse_perm_getattr(inode, mask);           // <---- HERE  ----
			if (err)
				return err;
		}
	}

	if (fc->default_permissions) {
		err = generic_permission(&init_user_ns, inode, mask);    // <---- AND HERE  ----
```

However, we are not so lucky in cases where a shared lock is used for inodes, like the "lookup" operation (i.e., finding directory child given a directory and the child's name). Those operations are meant to be read-only but still require a permission check (`x` permissions on the parent directory), which in case of FUSE means updating the parent directory's attributes. FUSE uses an additional spinlock for every inode (`struc fuse_inode->lock`) to make sure such parallel operation don't result in any data corruption but to my understanding this doesn't protect against one lookup operation updating `stuct inode*` while another one is checking permissions between the two lines of code I marked above. This may result in permission errors when directories have permissions like 750 (e.g., when umask is set to 007 when running `test.sh`) and one lookup updates the inode's `st_uid` just before another calls `err = generic_permission(...)`.

That said, I believe that the problem with the way your file system handles `st_uid` is changing this attribute in `getattr` operations, which Linux kernel is generally prepared for – it tries to allow such read-only file system operations to run in parallel for one inode. Linux expects that things like `st_uid` change in `setattr` where an exclusive inode lock is used.

When looking at the FUSE kernel sources though, I found something interesting – the `FUSE_PARALLEL_DIROPS` capability which is enabled by default in libfuse3 ([see here](https://github.com/libfuse/libfuse/blob/fuse-3.13.1/lib/fuse_lowlevel.c#L2039)). When the userspace file system implementation disables this by clearing the `FUSE_CAP_PARALLEL_DIROPS` bit in `struct fuse_conn_info->want` its `init` callback, the kernel module starts using an extra mutex to prevent parallel `readdir` or `lookup` operations on the same inode (see `fuse_lock_inode`). I still couldn't reproduce the problem you are reporting, but maybe you can try if disabling parallel directory operations in this way will make things any better.

**Comment by mpartel** [comment]
Thank you for the deep dive!

I tried `conn->want &= ~FUSE_CAP_PARALLEL_DIROPS;` in `xmp_init` but the test still fails. 

I'll try to get some understanding of the kernel code later, but you are certainly in a better position to evaluate how difficult this would be to fix. Naively, from your description it sounds like if FUSE allowed us to request that all operations take an exclusive lock, then we'd be good, right?

**Comment by bsbernd** [comment]
One way or the other, this is not a libfuse bug  - linux-fsdevel and fuse-devel are the right place to ask.

Assuming you would 'fix' the kernel without allowing parallel operations - you would slow down everything for an unknown use case. The vfs can do two assumptions

- local file system -> owner gets changed with chown -> default_permissions/generic_permission is typically safe()
- network file system -> owner might get changed on other nodes -> you need an access() method implemented and query the server for permissions

You case doesn't seem to match either of both, but is still similar to a network case - your daemon changes owner/permissions behind the back of the vfs - you will need to implement an access method and let your daemon decide. So from my point of view, bug in your implementation.

**Comment by mpartel** [comment]
Ok, I'll do that. Do you happen to know of an existing implementation I could use for reference, other than the kernel's?

I still think this deserves a mention in some comment or doc, because `getattr; operation` not being atomic like this is IMO very non-obvious, even if we don't want to call it a bug.
