### ISSUE TITLE
fuse: direct_io does nothing/has no effect on filesystem caching

### ISSUE THREAD

**Issue by birdie-github** [libfuse/libfuse#75]
My Windows partition is mounted this way:

`/dev/sda1      /mnt/windows     ntfs-3g defaults,direct_io       0 0`

However when I cache a 1GB file by doing this:

`cat 1GB.bin > /dev/null`

Both buffers and cache increase by 1GB which means fuse **double** caches the file which this option is meant to prevent.

System info:
kernel 4.7.2 vanilla
fuse-2.8.3-5.el6.i686 (centos 6.8)
ntfs-3g-2016.2.22-1.el6.i686

**Comment by Nikratio** [comment]
Do you have the same problem when you use the `fusexmp` example that comes with libfuse?

**Comment by birdie-github** [comment]
Could you tell me how this utility is meant to be used/tested?

**Comment by birdie-github** [comment]
Seems to be OK:

file size: 1 235 574 224 bytes

```
[birdie@localhost ~]$ free
             total       used       free     shared    buffers     cached
Mem:      16383332    3453000   12930332     486148      90368    1616624
-/+ buffers/cache:    1746008   14637324
Swap:            0          0          0
[birdie@localhost ~]$ free
             total       used       free     shared    buffers     cached
Mem:      16383332    4685528   11697804     486148      90376    2823240
-/+ buffers/cache:    1771912   14611420
Swap:            0          0          0
```

**Comment by jpandre** [comment]
ntfs-3g does not cache its input or output, only when the output data is targeted at the current end of file and  it does not end on a cluster boundary, it build a temporary buffer for the last cluster in order to extend it so that the written buffer ends at the cluster boundary and the lower levels need not merge the cluster with earlier contents. So this temporary buffer is limited to a single cluster.

IMHO the significant difference with fusexmp is that fusexmp opens the partition either RDONLY or WRONLY for each read or write, then it closes the partition immediately. As a consequence what is written is not kept in cache for subsequent reading. On the contrary, ntfs-3g opens the partition RDWR and keeps it open until the partition is unmounted, thus the written data is kept in cache in lower levels for subsequent reading, as you observed.

ntfs-3g should probably open with O_DIRECT. This might have an adverse effect on accessing metadata, but it is worth trying. If successful, fusexmp should also do so for educational purposes.

You might try mounting with option raw, which has definitely bad consequences on accessing metadata.

**Comment by jpandre** [comment]
Please test the patch I have uploaded to http://tuxera.com/forum/viewtopic.php?f=2&t=31182&sid=52d901b9696dbbacc89913fb23716fb6 for opening with O_DIRECT.

Also in my previous comment above, please read "try mounting with option sync" (instead of "option raw").

**Comment by birdie-github** [comment]
This patch makes no difference whatsoever.

`/tmp/ntfs-3g -o direct_io /dev/sda1 /mnt/windows`

The kernel reports these mount flags (from /proc/mounts)

`rw,noatime,user_id=0,group_id=0,allow_other,blksize=4096 0 0`

**Comment by birdie-github** [comment]
I tried mounted this way:

`/tmp/ntfs-3g -o raw /dev/sda1 /mnt/windows`

The result is the same: both buffers and cache memory grow by the size of the read file, so there's still double buffering at play.

**Comment by Nikratio** [comment]
I'm closing this issue, since it seems to be ntfs-3g specific.

As an aside, fusexmp is just a passthrough file-system (it doesn't work with partitions).

**Comment by birdie-github** [comment]
I'm not sure this bug might be closed that easily. I guess there must be a way to tell FUSE not to cache data twice in spite of the file system in use.

If there's nothing that can be done in FUSE itself, I hope you don't mind if we continue discussing NTFS-3G issue here.

**Comment by jpandre** [comment]
I have uploaded a new patch to the ntfs-3g forum (which is the right place for ntfs-3g issues).

I have however a question which might belong to fuse : the buffer passed to user space for reading or writing is not page aligned. Is this not a problem for lower level drivers having to make a direct io to/from the buffer ?

**Comment by Nikratio** [comment]
Let me reply with a number of somewhat independent points :-).

- As far as I know, direct-IO requires sector alignment, not page alignment (cf. https://lwn.net/Articles/12032/,https://www.quora.com/Why-does-O_DIRECT-require-I-O-to-be-512-byte-aligned).
- There is no buffer handed to userspace but a fd. libfuse is responsible for reading the data into a buffer (unless you're using splice, see below)
- As far as I know, libfuse doesn't guarantee sector alignment either (but it may simply mean that I haven't stumbed over the relevant code yet)
- Depending on your reasons for wanting to do direct-IO, using splice (i.e., `write_buf` and `fuse_reply_buf`) may be a better choice
- This isn't related to a client wanting to do direct-IO with the FUSE file system, but the FUSE file system wanting to do direct-IO on some other file system (but I assume you know that)
