### ISSUE TITLE
Clarification on Licensing of LGPL vs GPL portion

### ISSUE THREAD

**Issue by msays2000** [libfuse/libfuse#752]
Hi in many Linux distros we have to install fuse to use a fuse based mount. 

Can one please clarify the intent of having two licenses

- LGPL2 on userspace library (libfuse.*)
- GPL2 on fusermount (mount utility)

Why cannot both be under LGPL license that simplifies distribution clause!!

Many tools like rclone etc ( tool's list is in https://en.wikipedia.org/wiki/Filesystem_in_Userspace) execute fusermount dynamically to setup the mount point. 

My question is does needing to install fuse and executing fuserpoint dynamically by other mount tools qualify as distribution?  Is there a restriction on this distribution to use fusermount? 

Or does it not qualify as distribution and treated part of OS and license of OS governs it, since installing fuse is independent of installing fuse based mount software that uses it.

**Comment by msays2000** [comment]
@Nikratio please shed some light on GPL2 restrictions of using fusermount utility especially on installing/distribution part.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question related to libfuse, but not related to any bugs in the code. Therefore, could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

In short, I do not want to attempt to define "distribution" here because I think the term has a well understood meaning. Roughly speaking, it relates to making something available to someone else and is not directly related to execution of program code.

I am unfortunately not in a position to make any changes to license because there is a large number of other copyright holders. If it simplifies things, then you can safely use and distribute the entirety of libfuse under GPL2.


Thanks!
