### ISSUE TITLE
mount.fuse / fusermount missing in a FUSE3-only system

### ISSUE THREAD

**Issue by jengelh** [libfuse/libfuse#794]
Related reference: https://bugzilla.suse.com/show_bug.cgi?id=1210291

Do the `fusermount` and `fusermount3` programs do anything that is FUSE2/FUSE3-specific? Could we just hardlink the two names in a distro such that fusermount and fusermount3 are both the 3.x variant?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

As for your question, libfuse3 was developed to deliberately break backwards compatibility with libfuse2. Using libfuse2's  fusermount as fusermount3 will definitely break in some situations. Using fusermount3 as fusermount may or may not work (someone would have to go through the changes and check if there are any that break backwards compatibility), but it is certainly not a supported configuration.

**Comment by jengelh** [comment]
The Sourceforge project at https://sf.net/projects/fuse rather explicitly states "The FUSE project has moved to https://github.com/libfuse/". That's not ideal getting re-directed between SF and GH.

**Comment by Nikratio** [comment]
Not sure I understand. The Sourceforge page is correct. Libfuse has moved here (even though Libfuse2 is no longer developed).

How is that related to fusermount compatibility?
