### ISSUE TITLE
Accessing the value of `fsname`

### ISSUE THREAD

**Issue by koutheir** [libfuse/libfuse#802]
When using `fuse_parse_cmdline()` and `fuse_session_new()` with `-o fsname=<some-path>,...`, the function `fuse_session_new()` parses the value of `fsname` and stores it internally. Is there a way to query that value, given a `struct fuse_session*`? Or am I expected to do the parsing of `-o fsname=<some-path>,...` on my own before calling `fuse_session_new()`?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

As for your question, in most cases your own code would be *assembling* the string that is passed to `fuse_session_new`, so you shouldn't have a need to retrieve it afterwards.

Thanks!

**Comment by koutheir** [comment]
> Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker?

Sure, I'll ask there.
