### ISSUE TITLE
how to control io size and offset 4k alignment of fuse_lowlevel_ops

### ISSUE THREAD

**Issue by bigbrotherwei** [libfuse/libfuse#808]
First of all, thank you to the developers and maintainers of libfuse. I want to ask a question, not an issue. When I implement the read and write interfaces of fuse_lowlevel_ops, can I control whether the offset and size parameters of the interface are aligned according to the specified mode when io arrive at the interface, such as 4k alignment

example
```
static struct fuse_lowlevel_ops my_operations = {
    .read = my_read,
    .write = my_write,
};


// when it call my_read, the size and offset are aligned as 4k alignment
static void my_read(fuse_req_t req, fuse_ino_t ino, size_t size,
                    off_t offset, struct fuse_file_info *fi)
{
    printf("read");
    fuse_log(FUSE_LOG_INFO, "read:", ino, " offset:", offset, ", size:", size);
    char *buf = (char *)malloc(size);
    if (buf == NULL) {
        fuse_reply_err(req, ENOMEM);
        return;
    }

    int fd = fi->fh;
    ssize_t res = pread(fd, buf, size, offset);
    if (res == -1) {
        free(buf);
        fuse_reply_err(req, errno);
        return;
    }

    fuse_reply_buf(req, buf, res);
    free(buf);
}
```

when it call my_read, the size and offset are aligned as 4k alignment ,Is there any way to do that?

Thanks a lot !

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
