### ISSUE TITLE
Empty read right after write in multi-threaded fuse daemon

### ISSUE THREAD

**Issue by jerrychenhf** [libfuse/libfuse#809]
I have a python program write a file and then read from the file like following:
    
    if __name__ == '__main__':
        ip_config_file = "/path/to/fuse/mount/ip_config.txt"
        with open(ip_config_file, "w+") as f:
            f.write("{}\n".format("172.20.0.3"))

        with open(ip_config_file, "r") as f:
            for line in f:
                print(line)

I am using fuse_dfs (HDFS fuse implementation) and the file is stored on HDFS through fuse_dfs running the default multi-threaded mode.
The issue I found is that the read after the write is empty most of the time. If I put short sleep between write and read, I can read the right contents. 
I run in the debug mode and added more debug information and I found that the CLOSE of the file handle was delayed and showed up after the OPEN operation for the read operations, thus get the empty file contents, like following:

![image](https://github.com/libfuse/libfuse/assets/3349124/db212d3c-5489-41e7-bf4a-1da817cb6331)

The last hdfsCloseFile (unique: 970) is for the RELEASE call of the file for writing operation. But it is completed after read requests.

I know something may be done in the fuse HDFS to make this right. But I would like to get some help on a few points:
1. Is this the designed behavior for libfuse operating under multi-threaded? Shall f.close operation at application side (python code here) be blocked until the close is DONE (no matter sync or aysnc underlayer)?
2. Why the multi-threaded issue doesn't happen on the the operations of OPEN follwing with multiple WRITEs on the same file handle? Is there any special handle for the order of the operations of same file handle?
3. The request of read right after write in program is very common and what's the right way to handle this case right in user's fuse implementation?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

As for your question: the results of a WRITE request that completes before the beginning of a READ request must be reflected in the response to the READ request. If this is not the case, it is a bug in the FUSE filesystem (not in libfuse). This is also the case no matter if the filesystem is single threaded or multi-threaded.

**Comment by jerrychenhf** [comment]
Thanks @Nikratio for the response.  I'll close this.
