### ISSUE TITLE
Cannot rename symlink with overlayfs, if lowerdir is on FUSE

### ISSUE THREAD

**Issue by ruiwen-zhao** [libfuse/libfuse#834]
Hi all,

When I create an overlayfs with lowerdir on FUSE, and run `mv` command on a symlink through the overlayfs,  I will get a "No such device or address" error. 

The reproduction steps are as following:

On a Debian bookworm (kernel 6.1.0) VM:

1. Create a file and a symlink under the VM's root dir:
```
ruiwen@instance-1:/tmp$ ls / -l | grep foo
-rw-r--r--   1 root root     0 Aug 30 23:10 foo
lrwxrwxrwx   1 root root     3 Aug 30 23:12 foolink -> foo
```

2. Run libfuse's passthrough, which mounts a FUSE filesystem by mirroring the root dir:
```
ruiwen@instance-1:~/fuse-3.16.1/build/example$ ./passthrough -o allow_other /tmp/fusemount
ruiwen@instance-1:~/fuse-3.16.1/build/example$ ls /tmp/fusemount/ -l | grep foo
-rw-r--r--   1 root root     0 Aug 30 23:10 foo
lrwxrwxrwx   1 root root     3 Aug 30 23:12 foolink -> foo
```

3. Create a overlayfs, with lower dir being the the mount point of FUSE filesystem.
```
ruiwen@instance-1:/tmp$ mkdir -p fusemount upper work merged
ruiwen@instance-1:/tmp$ sudo mount -t overlay overlay -o lowerdir=fusemount,upperdir=upper,workdir=work merged
ruiwen@instance-1:/tmp$ ls -l merged/ | grep foo
-rw-r--r--   1 root root     0 Aug 30 23:10 foo
lrwxrwxrwx   1 root root     3 Aug 30 23:12 foolink -> foo
```

4. Move the symlink and see the failure:
```
ruiwen@instance-1:/tmp$ mv merged/foolink merged/foolink2
mv: cannot move 'merged/foolink' to 'merged/foolink2': No such device or address
```

I think this is a bug is more on linux kernel and overlayfs, because I found a similar issue reported on Debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049885). But I am not sure how I should proceed with this bug, so asking here trying to get some help.

**Comment by Nikratio** [comment]
Please run `passthrough` with debug output enabled, and post the messages that are printed when running the mv command.

**Comment by Nikratio** [comment]
This is most likely an issue in overlayfs that libfuse can do nothing about, or an issue in the fuse kernel module that libfuse can also do nothing about. But let's be sure.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, without additional information it's unlikely that anyone will be able to work on this. Furthermore, this project does not currently have any active, regular contributors, so even if you provide the necessary information, it may remain unfixed unless you also provide a a pull request or the issue clearly has high impact on a large number of users.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.
