### ISSUE TITLE
Makefile or meson ?

### ISSUE THREAD

**Issue by HeroKern** [libfuse/libfuse#863]
Why forgo Makefile and use meson？

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

As for your question, a quick Googling finds https://www.cs.cmu.edu/afs/club.cc.cmu.edu/usr/cmccabe/blog-notes/autotools_considered_harmful2.html which gives some potential reasons.
